apiVersion: v1
kind: Pod
metadata: 
  name: pod-init
spec:
  initContainers:
    - name: debug
      image: docker.io/rkalluru/learnk8s:init-container-html-generator
      volumeMounts:
      - mountPath: /mnt/html
        name: html
    - name: nginx
      image: nginx
      volumeMounts:
      - mountPath: /usr/share/nginx/html
        name: html
  volumes:
    - name: nginx
      emptyDir: {}    