apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    component: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      component: frontend
  template:
    metadata:
      labels:
        component: frontend
    spec:
      containers:
        - name: frontend
          image: public.ecr.aws/w8x4g9h7/roboshop-v3/frontend

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  labels:
    component: catalogue

spec:
  replicas: 3
  selector:
    matchLabels:
      component: catalogue
  template:
    metadata:
      labels: 
        component: catalogue
    spec:
      containers: 
        - name: catalogue
          image: public.ecr.aws/w8x4g9h7/roboshop-v3/catalogue
