apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    component: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      component: frontend
  template:
    metadata:
      labels:
        component: frontend
    spec:
      containers:
        - name: frontend
          image: public.ecr.aws/w8x4g9h7/roboshop-v3/frontend
          env:
            - name: CATALOGUE_HOST
              value: catalogue-ip
            - name: CATALOGUE_PORT
              value: "8080"
            - name: USER_HOST
              value: host
            - name: USER_PORT
              value: "8080"
            - name: CART_HOST
              value: cart
            - name: SHIPPING_HOST
              value: shipping
            - name: SHIPPING_PORT
              value: "8080"
            - name: PAYMENT_HOST
              value: host
            - name: PAYMENT_PORT
              value: "8080"
            
    

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  labels:
    component: catalogue

spec:
  replicas: 3
  selector:
    matchLabels:
      component: catalogue
  template:
    metadata:
      labels: 
        component: catalogue
    spec:
      containers: 
        - name: catalogue
          image: public.ecr.aws/w8x4g9h7/roboshop-v3/catalogue
