apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.component }}
  lables:
    component: {{ .Values.component }}
spec:
    replicas: 1 
    selector:   
      matchLables:
        component: {{ .Values.component }}
    template:
      metadata: 
        lables: 
          component: {{ .Values.component }}
      spec:  
        containers:
        - name: {{ .Values.component }}
          image: public.ecr.aws/w8x4g9h7/roboshop-v3/{{ .Values.component }}  